### ISSUE TITLE
Support for "browser history"

### ISSUE THREAD

**Issue by Puffton** [julienschmidt/httprouter#102]
Using single page applications it's common to implement "browser history" (for example like react-router has done).

I'm using a NotFound-handler for my static files (I don't want my users to see /static/index.html for example in their URL):
```go
  r.NotFound = Compress(http.FileServer(http.Dir("../static")))
```

But I would also like to use a wildcard-handler for all actual "NotFound" requests, this is because the browser history will generate URLs on the client side. If the page is refreshed, it will request these URLs (that don't exist on the server side), expecting index.html back.

Please see: https://github.com/rackt/react-router/blob/master/docs/guides/basics/Histories.md#createbrowserhistory

**Comment by julienschmidt** [comment]
Then your NotFound handler should decide if it has to deliver a static file, call a specific handler (e.g. another HttpRouter instance) or throw an actual 404 error (which the handler could do to simplify it a bit)
