### ISSUE TITLE
Retrieving IP addresses with .ByName cause panic.

### ISSUE THREAD

**Issue by twisted1919** [julienschmidt/httprouter#103]
Url: `http://localhost:8000/check/89.164.12.89`  
Route: `router.GET("/check/:ip", setupHTTP(httpHandler))`  
Result: `2015/10/12 22:21:02 http: panic serving 127.0.0.1:60851: runtime error: index out of range`  
Any idea why this happens?

**Comment by vivekrajr** [comment]
@twisted1919 

Could you please give more details? The following snippet worked fine for me

```go
package main

import (
	"fmt"
	"github.com/julienschmidt/httprouter"
	"net/http"
)

func main() {
	router := httprouter.New()
	router.GET("/check/:ip", IPHandler)

	http.ListenAndServe(":9090", router)
}

func IPHandler(w http.ResponseWriter, r *http.Request, p httprouter.Params) {
	ip := p.ByName("ip")
	fmt.Fprintf(w, ip)
}
```

**Comment by twisted1919** [comment]
@vivekrajr - Managed to fix this meanwhile, was a false alarm.
