### ISSUE TITLE
Why not use official Clean func?

### ISSUE THREAD

**Issue by AnotherGoogleFans** [julienschmidt/httprouter#109]
I read your source code. And I see the CleanPath function.
I guess it has the same effect with the Clean function in package path or path/filepath that golang supported itself.
Why not use it directly? Why write this function yourself? Any differences between these functions?

**Comment by vivekrajr** [comment]
As specified in the documentation, CleanPath is a URL version of path.Clean

Few differences
```path.Clean("")``` is ```.``` while ```CleanPath("")``` is ```/```
```path.Clean("/abc/")``` is ```/abc``` while ```CleanPath("/abc/")``` is ```/abc/```
```path.Clean("abc/../../././../def")``` is ```../../def``` while ```CleanPath("abc/../../././../def")``` is ```/def```

These are some of the examples
