### ISSUE TITLE
case insensitive path matching doesn't work for unicode paths

### ISSUE THREAD

**Issue by rogpeppe** [julienschmidt/httprouter#113]
To demonstrate, add a 	"/Π" entry to routes in TestTreeFind and

    		{"/π", "/Π", true, false},

to the tests table.

The reason is because we findCaseInsensitivePath is assuming that it can use
strings.ToLower on a single byte to determine which node to descend into,
but this is not valid on unicode characters. The correct solution is probably
to add a lower-cased node for all entries - then the usual lookup logic
could be used with the lower-cased lookup path.

**Comment by julienschmidt** [comment]
Unicode stuff can be really complicated sometimes, but I think I still found a more or less nice solution. Please test if it works properly now.
It still doesn't do normalization, but unless someone shows me a good reason to do that, I don't plan to implement it.
