### ISSUE TITLE
Method: "Any"

### ISSUE THREAD

**Issue by pjebs** [julienschmidt/httprouter#118]
How can I not discriminate against a method name.
Sometimes I don't care if it's POST or GET or whatever. I just want the url to link to the handler. How can I do that?

**Comment by EtienneBruines** [comment]
Just wondering; why would you want this? I mean, if you don't care, it's usually a `GET` request:
* If it's not a `GET` request (i.e. `POST`), but you act as if it were a `GET` request, then it should **be** a `GET` request and not a `POST` request. 

You could always add the same `Handler` for both `GET` and `POST` if you *really* wanted to do it, but I would feel like it would encourage bad behavior. 

(Also, I do not mean to offend you / anyone else, and would like to reminder you that I am not a contributor of this repo)

**Comment by julienschmidt** [comment]
See also #72

**Comment by sevoma** [comment]
A valid use case for this is for a reverse proxy. I have a few endpoints for SAML auth, but any other request to any other endpoint I want to go through the reverse proxy. Maybe i'm approaching this wrong?

**Comment by tmthrgd** [comment]
@sevoma It sounds like you should use the `NotFound` handler (['Chaining with the NotFound handler' - README.md](https://github.com/julienschmidt/httprouter/blob/18be18fd6dc6db3aa2d279fa5c4fa4518a970201/README.md#chaining-with-the-notfound-handler)) for the proxy and register the SAML endpoints with the router.
