### ISSUE TITLE
Subroutes

### ISSUE THREAD

**Issue by SlevinT** [julienschmidt/httprouter#125]
Does httprouter allow for subroutes?

**Comment by Annonomus-Penguin** [comment]
Not by default. However, a framework like Gin (built upon httprouter) *does* indeed allow this

**Comment by SlevinT** [comment]
oh ok and speed difference? I use http router for one project, but for another I want the speed to be there.

**Comment by SlevinT** [comment]
Nevermind just benchmarked lol... a lot faster than gorilla for rest.

**Comment by Annonomus-Penguin** [comment]
For Gin? Gin is just another layer on top of httprouter.

Yeah, it is a lot faster.

**Comment by julienschmidt** [comment]
Also take a look at #89 
v2 (soon™) will have subrouters (probably just a struct with prefix strings) for convenience. You could also build a wrapper on your own.

**Comment by SlevinT** [comment]
Thanks for that @julienschmidt, and btw love this so far.
