### ISSUE TITLE
Option to use 302 redirect instead of 301

### ISSUE THREAD

**Issue by Anon-Penguin** [julienschmidt/httprouter#128]
Permanent redirects can get messy and they've bitten me a few times. I would like a way to use temporary redirects instead for `RedirectTrailingSlash` and `RedirectFixedPath`.

I assume this is something that we have to wait for V2 for? Or is there a way to add a non-breaking addition that would allow this, like an extra function that sets this setting?

**Comment by julienschmidt** [comment]
301 redirects are very much intended in these cases. v2 won't have support for 302 redirects either. You should **never** have the same route with / without trailing slash or routes with the same semantic meaning serving different content at the same time.

**Comment by Anon-Penguin** [comment]
No. I'm saying do 302s on request so the capitalization/trailing slash setup can be changed in the future (changing the URL naming pattern). So, if I wanted to rename "Hello" to "hello", I wouldn't be stuck in a redirect loop.

I wasn't thinking it through enough when I posted it. A lot of this should be standardized from day one, and any changes in capitalization in URLs (like post titles) would be in a parameter and thus handled by the handler and not httprouter. This would also cover the case of URL shorteners, where case sensitivity is common to get a shorter URL.

Still, I think it might be an okay feature to have in rare cases (unification of redirect codes to simplify API docs, any case where there is a possibility of an evolving URL pattern, etc.), but those cases I'd be willing to manually fork and implement if I would ever need it.

**Comment by Anon-Penguin** [comment]
Sorry for bothering you :)
