### ISSUE TITLE
OPTIONS method missing from Allow header

### ISSUE THREAD

**Issue by danilobuerger** [julienschmidt/httprouter#132]
In reference to #98 the OPTIONS method seems to be missing from the Allow header on OPTIONS requests or method not allowed. However since the native OPTIONS support from https://github.com/julienschmidt/httprouter/commit/5273944025bdfe8df6c10f286ce7742b83673033 every defined route supports this method so should be listed in the Allow header.

**Comment by julienschmidt** [comment]
You are right. Should be fixed now.
Thanks!
