### ISSUE TITLE
Http PUT method support?

### ISSUE THREAD

**Issue by kyawmyintthein** [julienschmidt/httprouter#136]
I use httprouter for routing. But, I cannot use PUT method in html submit. Is it support for http PUT method in httprouter?

**Comment by ChristianSiegert** [comment]
@kyawmyintthein If you want to handle PUT requests, you can use [Router.PUT](https://godoc.org/github.com/julienschmidt/httprouter#Router.PUT) and [Router.Handle](https://godoc.org/github.com/julienschmidt/httprouter#Router.Handle).

Please note: HTML forms do not support the PUT method. Even if you set up httprouter correctly, GET and POST are the only allowed methods for submitting an HTML form. [See StackOverflow Question #8054165](http://stackoverflow.com/questions/8054165/using-put-method-in-html-form).

**Comment by kyawmyintthein** [comment]
Thanks @ChristianSiegert
