### ISSUE TITLE
HTML5 Routing

### ISSUE THREAD

**Issue by ericmccarthy7** [julienschmidt/httprouter#137]
Having issues using angular2 routing with httprouter.

I've looked through [this](https://github.com/julienschmidt/httprouter/issues/70) and [this.](https://github.com/julienschmidt/httprouter/issues/93)

Haven't been able to get either solutions to work. If I use
`router.ServeFiles("/*filepath", http.Dir("static"))`

It lets me display the app, however if I try to access /dashboard directly it throws a 404.

```
router := httprouter.New()
router.NotFound = http.FileServer(http.Dir("static/index.html"))
http.ListenAndServe(":8080", router))
```

Above caused a redirect loop somehow.

and I'm using the plunkr from [here](https://angular.io/resources/live-examples/toh-5/ts/plnkr.html)

Thanks for any help

**Comment by kbrah** [comment]
I have the exact same problem. I see this is not very new comment. Have you managed to make it work?

**Comment by wwwdata** [comment]
of course the `http.Dir` will try to load the file `Dashboard` because you serve a directory. You should implement a NotFound handler that just reads your `index.html` from disk and always returns that. This should work.

**Comment by julienschmidt** [comment]
@wwwdata's solution should work.You can use https://golang.org/pkg/net/http/#ServeFile
The default mux of net/http should however be a better fit, since you don't seem to do any actual server-side routing.
