### ISSUE TITLE
Adding routes after router is serving

### ISSUE THREAD

**Issue by VoidingWarranties** [julienschmidt/httprouter#138]
Is there a safe way to add routes after a router is serving requests? Running the following with the go race detector catches a data race in access to the underlying tree. Is there a safer way to do this?

e.g.
```go
package main

import (
        "fmt"
        "log"
        "net/http"
        "time"

        "github.com/julienschmidt/httprouter"
)

func Index(w http.ResponseWriter, r *http.Request, _ httprouter.Params) {
        fmt.Fprint(w, "Welcome!\n")
}

func Hello(w http.ResponseWriter, r *http.Request, ps httprouter.Params) {
        fmt.Fprintf(w, "hello, %s!\n", ps.ByName("name"))
}

func main() {
        router := httprouter.New()
        router.GET("/", Index)

        go func() {
                time.Sleep(1 * time.Second)
                router.GET("/hello/:name", Hello)
        }()
        log.Fatal(http.ListenAndServe(":8080", router))
}
```

**Comment by ChristianSiegert** [comment]
@VoidingWarranties Out of curiosity, what is the use case for adding routes after the router is serving requests?

**Comment by VoidingWarranties** [comment]
The [Sia daemon](https://github.com/NebulousLabs/Sia) incrementally starts up as new modules are loaded. Currently we only register routes after all modules have started up. We want a way to have the API startup immediately, but somehow indicate that some routes are not yet available.

I realize now that the solution I proposed in this issue isn't ideal as routes for unloaded modules would return 404, whereas it would make more sense to return 503.

**Comment by julienschmidt** [comment]
As you already noticed, adding routes late is a bad idea.
Not only should routes which later become available throw an `503` error, adding routes can also change the semantics of existing routes.
Adding routes late is therefore an anti-feature. I'd rather add code to make the tree immutable after starting to serve routes.

**Comment by Thomasdezeeuw** [comment]
Hello @VoidingWarranties, the code below might work for your situation.

```go
package main

import (
	"fmt"
	"net/http"
	"sync"

	"github.com/julienschmidt/httprouter"
)

func main() {
	// Only add the home page
	routes["/"] = Index

	r := NewRouter()

	// TODO: Add error handling etc.
	var errC = make(chan error, 1)
	go func() {
		errC <- http.ListenAndServe(":8080", r)
	}()

	// Add the Hello route
	routes["/hello/:name"] = Hello

	// Update the available routes.
	r.UpdateRouter()

	err := <-errC
	if err != nil {
		panic(err)
	}
}

func Index(w http.ResponseWriter, r *http.Request, _ httprouter.Params) {
	fmt.Fprint(w, "Welcome!\n")
}

func Hello(w http.ResponseWriter, r *http.Request, ps httprouter.Params) {
	fmt.Fprintf(w, "hello, %s!\n", ps.ByName("name"))
}

var routes = make(map[string]httprouter.Handle)

func createRouter() *httprouter.Router {
	r := httprouter.New()

	for url, handle := range routes {
		r.GET(url, handle)
	}

	return r
}

type Router struct {
	mu     sync.RWMutex
	router *httprouter.Router
}

func (r *Router) UpdateRouter() {
	r.mu.Lock()
	defer r.mu.Unlock()
	r.router = createRouter()
}

func (r *Router) ServeHTTP(w http.ResponseWriter, req *http.Request) {
	r.mu.RLock()
	// Keep the defer statement, this way it will release the lock, if if the code
	// panics.
	defer r.mu.RUnlock()

	r.router.ServeHTTP(w, req)
}

func NewRouter() *Router {
	return &Router{
		router: createRouter(),
	}
}
```

I must warn that adding a global mutex like this will reduce the throughput of your application.
