### ISSUE TITLE
Cannot find package

### ISSUE THREAD

**Issue by itsverygood** [julienschmidt/httprouter#14]
I am new to go. I copy your example from usage and build it. I got error.

c:\Apps\Google\Projects\myGoAppWebstorm\src>go build myGoAppWebstorm.go
myGoAppWebstorm.go:5:5: cannot find package "github.com/julienschmidt/httprouter
" in any of:
        C:\Go\src\pkg\github.com\julienschmidt\httprouter (from $GOROOT)
        C:\Apps\Google\Projects\src\github.com\julienschmidt\httprouter (from $G
OPATH)

What am I doing wrong?

**Comment by erdiugurlu** [comment]
If you are still getting this error, close your editor(Visual Studio Code etc.) and remove dirty files in the directory of your  computer. Afterwards, try to run the command above on Windows Command Line/ Git Bash.

**Comment by matialvarez7** [comment]
A have this problem in Linux when i try to install with go install github.com/julienschmidt/httprouter@latest:

package github.com/julienschmidt/httprouter is not a main package

What can i do?
