### ISSUE TITLE
Encapsulate path params in url.Query and use net/http idiomatic only interface

### ISSUE THREAD

**Issue by h2non** [julienschmidt/httprouter#142]
One of things I believe could be drastically simplified in terms of router handler function interface is avoiding the `httprouter` interface specific notation turning it into a more idiomatic, less instrusive and simple interface that would fit perfectly with the native `http.HandlerFunc` interface. This should also remove the friction when adopting this library without forcing to refactor any function interface.

Let me explain this with some examples.

Instead of having the following function signature, which is `httprouter` specific and no more:
```go
func Hello(w http.ResponseWriter, r *http.Request, ps httprouter.Params) {
    fmt.Fprintf(w, "hello, %s!\n", ps.ByName("name"))
}
```

Use a simple interface who reuses `url.Query` interface to overload it exposing the parsed path params and provides a full `http.HandlerFunc` compatible interface which is considerable more interporable and removes type specific coupling to `httprouter` package:
```go
func Hello(w http.ResponseWriter, r *http.Request) {
    fmt.Fprintf(w, "hello, %s!\n", r.URL.Query.Get(":name"))
}
```

Essentially, path params should be exposed via `url.Query` as standard URL query params but with a different notation, perhaps `:name` to follow the same path declaration idiom, but other could other as well, such as: `@name` or `%name`.

This proposal should be simple to support and very useful IMO. I understand that it implies breaking existent interfaces, so my proposal is to support it the future `v2` or alternatively support some sort of interface overloading as router handlers supporting both function interfaces in the current version.

**Comment by namnm** [comment]
+1 I found some other router libs do this as well

**Comment by julienschmidt** [comment]
As explained in the README, using url.Query is inefficient. However with Go 1.7 a Context might be an alternative (see #147)
