### ISSUE TITLE
Sublicensing

### ISSUE THREAD

**Issue by ndbeals** [julienschmidt/httprouter#146]
I'm a little confused as to the terms of the license on this project. Does it allow sublicensing?

**Comment by julienschmidt** [comment]
I'm not sure what you mean by sublicensing. You may use this software in any other project as long as you follow the conditions for redistribution. Re-licensing to a compatible license (that means stricter) is also possible. Please refer for to other sources for legal information on that.

See here for a good summary: https://tldrlegal.com/license/bsd-3-clause-license-%28revised%29

**Comment by ndbeals** [comment]
I did not realise your license was the BSD Three Clause license. My confusion came from the fact the MIT explicitly allows sublicensing while the BSD license does not, but nor does it disallow it. 

Thanks for the clarification anyways.
