### ISSUE TITLE
Communication

### ISSUE THREAD

**Issue by kataras** [julienschmidt/httprouter#149]
@julienschmidt Sorry for posting here but I couldn't find a way to communicate, can you give me informations in order to communicate with you (gitter, a chat, an active e-mail) or contact with me via [twitter](https://twitter.com/MakisMaropoulos) in order to solve the contradistinction between us? otherwise I think that we are ok now. I didnt understand your last sentence, I told you I am not native english, you have to explain me directly

**Comment by julienschmidt** [comment]
You can contact me via email: floss at julienschmidt dot com. We can find a more convenient communication channel via email then.

**Comment by kataras** [comment]
Julien Schmitt is a Fashion Editor and Stylist based in Paris. He studied at Studio Berçot in Paris. Right after his graduation, he assists Marie-Amélie Sauvé for ...
