### ISSUE TITLE
misleading panic message with non matching wildcard paths params

### ISSUE THREAD

**Issue by bithavoc** [julienschmidt/httprouter#151]
First off thanks for coming up with this library, it rocks :metal: 

Now, while trying to register the following two routes:
`/v1/properties/:id/subscriptions`
`/v1/properties/:property_id/notifications/:notification_id/clicks`

I'm getting the following error:
```
panic: path segment ':property_id/notifications/:notification_id/clicks'
  conflicts with existing wildcard ':id' in path
    '/v1/properties/:property_id/notifications/:notification_id/clicks'
```

I get what the validation is trying to say, but the message is misleading, it's saying that the conflict is in the route being registered and not in the route already registered, so it should say instead `conflicts with existing wildcard ':id' in path '/v1/properties/:id/subscriptions`.

**Comment by julienschmidt** [comment]
Sorry for the slow response. The full path of the already existing route is not available at this point (there might be many), but the existing prefix can be reconstructed.

For your given example, the panic reason now looks like this: `panic: ':property_id' in new path '/v1/properties/:property_id/notifications/:notification_id/clicks' conflicts with existing wildcard ':id' in existing prefix '/v1/properties/:id'`
