### ISSUE TITLE
Is httprouter not made for web apps?

### ISSUE THREAD

**Issue by chrisolsen** [julienschmidt/httprouter#153]
Below is a common scenario for web apps, but results in a route conflict, does not that mean httprouter is not meant for html web apps? Or is there a way around this while still keeping the routes consistent?
```
r.GET("/accounts/new", newHandler)
r.GET("/accounts/:id", showHandler)
```

**Comment by rickb777** [comment]
This is a design feature. You can use this instead:

```
r.GET("/accounts/new", newHandler)
r.GET("/accounts/id/:id", showHandler)
```

**Comment by kpurdon** [comment]
```
r.POST("/accounts", newHandler)
r.GET("/accounts/:id", showHandler)
``` 

This is supported by httprouter. HTTP Verbs FTW.

**Comment by falmar** [comment]
@kpurdon I'm pretty sure your example is more like an API than rather simple web app SEO friendly

**Comment by kpurdon** [comment]
@falmar fair, did not read issue thoroughly. @rickb777 this is a specific feature of httprouter.

**Comment by chrisolsen** [comment]
@rickb777 Currently I am tweaking the route names to make things works, but I was really hoping there was a better way.

**Comment by mikegleasonjr** [comment]
The original example given can be written in another way for it to work but still this is a problem of not being able to specify 2 similar routes, one with a parameter and another without.

**Comment by eriklott** [comment]
> This is a design feature.

@rickb777 I actually chuckled when I read that. Maybe you mean to say "This is a technical constraint"?

**Comment by julienschmidt** [comment]
#73 is what you're looking for now. For now it is a "design feature".

**Comment by julienschmidt** [comment]
#73 is what you're looking for. For now it is a "design feature".
