### ISSUE TITLE
[questinon] make map with parameters

### ISSUE THREAD

**Issue by spouk** [julienschmidt/httprouter#155]
How to create ways to map the parameters to be used in the logic in templates, for example:
in template 

`{{if eq $path "/posts/:posts" }} some logic {{end}} 
`

but I can not do, router provides the only way to end without the possibility of multiple selection

`{{if eq $path "/posts/somearticle" }} some logic {{end}} 
`

this really suxx. 

I try make mapper use adress memory handler for key + path, but httprouter use radix tree and fucken handler have one stupid memory address for multiple handlers.

**Comment by julienschmidt** [comment]
Sorry, but the question as given makes no sense to me.
If the question still exists, please add example code.

**Comment by falmar** [comment]
Seems he wants to compare or to know if the current url match the pattern.

**Comment by julienschmidt** [comment]
#139 ?
