### ISSUE TITLE
#148 happens again

### ISSUE THREAD

**Issue by dlsniper** [julienschmidt/httprouter#160]
Just to let you know, #148 seems to be happening again.
Please double check but there's no more third-party licenses nor anything similar in the root of the project and the history has been wiped again.

**Comment by kirillDanshin** [comment]
avelino/awesome-go#1135 merged.

**Comment by peterbourgon** [comment]
[The commit that stripped the LICENSE](https://github.com/kataras/iris/commit/5c98c5a493198adb3d5cd05e12ebc89e6a0884b3#diff-9879d6db96fd29134fc802214163b95aL23).

**Comment by julienschmidt** [comment]
[Nulled and fixed](https://github.com/kataras/iris/blob/87e18aa10b17cb8e21f908a6e7ec04f347d16047/LICENSE#L172)

**Comment by kirillDanshin** [comment]
@julienschmidt hope it never happen again

**Comment by kirillDanshin** [comment]
thanks for awesome package!

**Comment by kryptodev** [comment]
@julienschmidt lol you're quite the scum xD

**Comment by dlsniper** [comment]
@julienschmidt I deeply apologize for @kryptodev's behavior.
