### ISSUE TITLE
Proposal: change the type of handle in router methods

### ISSUE THREAD

**Issue by rezxv** [julienschmidt/httprouter#165]
Currently, the type for `handle` parameter for `httprouter.Router` functions, for example `httprouter.Router.Handle`, is `httprouter.Handle` which is an alias of `func(http.ResponseWriter, *http.Request, Params)` . The parameter type should be `func(http.ResponseWriter, *http.Request, Params)` instead. So, it will be `func (r *Router) Handle(method, path string, handle func(http.ResponseWriter, *http.Request, Params))`.

With this change, I can alias it in my package and could still use the instances with httprouter.

Note that this is the pattern the `net/http` use. For example, although there's `http.HandlerFunc` type which is an alias of `func(ResponseWriter, *Request)`, many of the functions, e.g., `http.ServerMux.HandleFunc`, are actually using the type of `func(ResponseWriter, *Request)` directly for their `handler` parameters instead of `http.HandlerFunc`.

**Comment by rezxv** [comment]
An illustration here: https://play.golang.org/p/hgrdboGxvt

If you uncomment the last commented line, you'll get a compile error.

**Comment by julienschmidt** [comment]
This shouldn't be an issue with Go 1.9+ anymore. Just use an alias: `type myHandleFunc = pkgHandleFunc`

Adjusted playground example: https://play.golang.org/p/pUt57Wu-LKn
