### ISSUE TITLE
project structure?

### ISSUE THREAD

**Issue by sgim74528** [julienschmidt/httprouter#168]
blog
---- comment
-------- controller.go
-------- model.go
-------- router.go
 ---- post
-------- controller.go
-------- model.go
-------- router.go
---- account
-------- controller.go
-------- model.go
-------- router.go
---- admin
-------- controller.go
-------- model.go
-------- router.go
---- main.go

I will make rest api service.

I want to develop as above.
Is it possible with httprouter?

Can you tell me how to do it?
I do not know how you think.

Please...

**Comment by Furdarius** [comment]
It's not about routing.

Some articles about repo organizing:
https://medium.com/@benbjohnson/standard-package-layout-7cdbc8391fc1#.jno1ncyv0
https://medium.com/@cep21/package-proliferation-mistakes-in-go-493664cde6b9#.fh4lfuclr
http://stackoverflow.com/questions/14867452/what-is-a-sensible-way-to-layout-a-go-project

**Comment by mbesancon** [comment]
@julienschmidt maybe close this issue
