### ISSUE TITLE
Moving from httprouter.Params to http.Request.Context?

### ISSUE THREAD

**Issue by jabbrwcky** [julienschmidt/httprouter#170]
Would it be possible to migrate from httprouter.Params to net.http.Request.Context/WithContext, now that the contexts are core part of go starting with 1.7?

This could make httprouter usable as a real drop-in replacement, which would be awesome IMO

**Comment by Thomasdezeeuw** [comment]
See https://github.com/julienschmidt/httprouter/pull/147.

**Comment by jabbrwcky** [comment]
Ah, did not find that in the first try. Thanks
