### ISSUE TITLE
Not a bug, is it a typo?

### ISSUE THREAD

**Issue by ruishengyang** [julienschmidt/httprouter#171]
The member called `handeled` of `handlerStruct`, it seems like a typo(`handled`)?  https://github.com/julienschmidt/httprouter/blob/master/router_test.go#L71

```
type handlerStruct struct {
	handeled *bool
}
```

It isn't a bug, sorry for the inconvenience.

**Comment by julienschmidt** [comment]
I saw this bug report just now. Thanks for reporting it, I fixed the typo now.
