### ISSUE TITLE
wildcard conflict should panic but doesn't

### ISSUE THREAD

**Issue by mbertschler** [julienschmidt/httprouter#172]
This code panics: `panic: catch-all routes are only allowed at the end of the path in path '/api/*rest/two'`
```go
router := httprouter.New()
router.GET("/api/*rest/two", handler)
router.GET("/api/*rest", handler)
```

But this one doesn't.
```go
router := httprouter.New()
router.GET("/api/*rest", handler)
router.GET("/api/*rest/two", handler)
```
As far as I understand it the router should  behave the same in the two cases, or am I missing something?

**Comment by julienschmidt** [comment]
In the second case one of the two routes is unreachable. However, this does not seem to be detected during registration, which is a bug.

**Comment by chahat-arora** [comment]
@julienschmidt Hey, any progress on this?
