### ISSUE TITLE
conflict between 2 routes that shouldn't happen ?

### ISSUE THREAD

**Issue by tjannaud** [julienschmidt/httprouter#175]
hi
I have routes:

    "/v1/a/:name"
    "/v1/a/user/selection"

since :name doesn't match / these 2 routes should not conflict but they do. Can you confirm?

**Comment by julienschmidt** [comment]
Unfortunately this is correct, which is one of the drawbacks of prefix matching like tries (aka. prefix trees) perform it.

After the prefix `/v1/a/` it can not tell if `:name` or `user` should be chosen. The router does not have a "global view", i.e. it does not know all possible sub-routes without actually trying them.
The only ways to to resolve this is to either let "static" segments like `user` always have preference over dynamic ones like `:name`, which is currently the plan for v2, or perform backtracking.
Backtracking means trying one route and if it can not be matches go up the tree again and try the alternative route. However, this makes the behavior of the router a lot less obvious and the routing more complex, e.g. it requires that nodes have knowledge of the parent node, which is currently not the case. The much bigger question is however, in which order the routes should be tried.

The design decisions for the current version was, that at any time a URL path can match at most one route. Thus, it is illegal to register `/v1/a/:name` and `/v1/a/user` at the same time, regardless of `/v1/a/user` being only used as a prefix for the actual route `/v1/a/user/selection`. To resolve it, register `/v1/a/:name/selection` instead and manually make sure that `:name` has the value "user" in the handler of the route.

**Comment by tjannaud** [comment]
Thanks for the `/v1/a/:name/selection` tip
