### ISSUE TITLE
How to write a logger for all requests?

### ISSUE THREAD

**Issue by dragfire** [julienschmidt/httprouter#177]
Using `net/http`, I can easily write a global logging midlleware.

```
// this handles all requests 
http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
	log.Info(r.Method, r.URL.Path)
})
```

I have to specify `REQUEST METHOD` on every handlers in `httprouter`. 
Is it possible to write such a middleware using `httprouter`?

**Comment by artem-malko** [comment]
@dragfire Hello. As I think, this job is not for router. It will be much better to use negroni, for example. https://github.com/urfave/negroni

**Comment by julienschmidt** [comment]
The router only does the routing, nothing else.
However, it is just a regular http.Handler, which can be chained. Either using e.g. negroni, or just with a simple Handler like the following (completely untested):
```go
type Logger {
    handler http.Handler
}

func (l *Logger) ServeHTTP(w http.ResponseWriter, r *http.Request) {
    log.Info(r.Method, r.URL.Path)
    handler.ServeHTTP(w, r)
}


func main() {
    router := httprouter.New()
    // ...

    log.Fatal(http.ListenAndServe(":8080", Logger{router}))
}
```
