### ISSUE TITLE
wildcard route conflicting when using Named parameters

### ISSUE THREAD

**Issue by thincal** [julienschmidt/httprouter#185]
There are only two rules:

```
    router := httprouter.New()
    router.GET("/resource/session/:filter", Index)
    router.GET("/resource/:name", Hello)
```

but why report error: `panic: wildcard route ':name' conflicts with existing children in path '/resource/:name'` ?

It seems that it doesn't match with [document](https://github.com/julienschmidt/httprouter#named-parameters).

**Comment by Thomasdezeeuw** [comment]
See #175.
