### ISSUE TITLE
Release v2

### ISSUE THREAD

**Issue by tochka** [julienschmidt/httprouter#186]
It'll be great if you release v2.
If you are woried about back comatability then you can use gopkg.in service to provide access to the new version.

**Comment by julienschmidt** [comment]
It will be released when it is done. See https://github.com/julienschmidt/httprouter/milestone/1 / https://github.com/julienschmidt/httprouter/projects/1. I'm currently lacking time for FLOSS development. I hope to consolidate my unreleased experiments into an experimental branch soon, however I really can't give any ETA.
