### ISSUE TITLE
What are the logic and algorithm in tree.go?

### ISSUE THREAD

**Issue by pathbox** [julienschmidt/httprouter#194]
Hi, 
  I read the codes in tree.go, but I can't understand how it works. Could you describe What  the logic and algorithm are in tree.go ?  
  Thank you very much.

**Comment by kiljacken** [comment]
As desribed in the [README](https://github.com/julienschmidt/httprouter#how-does-it-work), httprouter uses a Radix tree.

**Comment by pathbox** [comment]
Thanks a lot
