### ISSUE TITLE
Before/After functions for every route

### ISSUE THREAD

**Issue by KillingSpark** [julienschmidt/httprouter#195]
I would like to implement a feature that allows the user to register a function, to be executed before every route's handle and another one after every route's handle, to make things more convenient. I would use it for example, to check a custom header in the request. The solution I use currently, uses a Handler wrapped around every route there is, like in the authorisation example. Would like this feature in your library?

**Comment by rogierverbrugge** [comment]
You mean middleware?

**Comment by KillingSpark** [comment]
I feel kinda dumb as I learned about those a day after I wrote this. Can you or some mod delete the Issue?

**Comment by julienschmidt** [comment]
Completely deleting is not possible. Just close it
