### ISSUE TITLE
v1.2 release timeline?

### ISSUE THREAD

**Issue by rcorre** [julienschmidt/httprouter#207]
Hi, is there a timeline for the release of 1.2? I see there are still a few outstanding commits on the [milestone](https://github.com/julienschmidt/httprouter/milestone/2), but [`1.1`](https://github.com/julienschmidt/httprouter/releases/tag/v1.1) points to a commit about two years old. Users of dependency managers like glide will likely pin their dependency on `httprouter` to the latest release (`1.1`) and get a very old version of `httprouter`.

Is it reasonable to either finish the `1.2` blockers soon or push them to a later release?

**Comment by cooldarkdryplace** [comment]
Same goes for [dep](https://github.com/golang/dep). It tries to stick to latest tag by default.

**Comment by sharpner** [comment]
We also got a few [bug reports](https://github.com/manyminds/api2go/issues/304) in the past because our library sticks to your master version and more and more people use dep. Any plans for a new release?

**Comment by sugarjig** [comment]
Any new developments on this? It would be nice to have a release version that wasn't nearly 3 years old...

**Comment by elukey** [comment]
Same question from me :)

I am trying to build Linkedin's Burrow with Debian Sid's golang-github-julienschmidt-httprouter-dev (that is still stuck at the 1.1 tag) and it fails since so many things have changed in the meantime. A 1.2 release would probably also kick off a new debian sid version that would be really appreciated!

Thanks in advance!

**Comment by danielspk** [comment]
+1
Using go 1.11 modules: github.com/julienschmidt/httprouter v0.0.0-20150421170007-8c199fb6259f

**Comment by Megalepozy** [comment]
+1

**Comment by julienschmidt** [comment]
See #249. Tagged a new release.
