### ISSUE TITLE
Single page app with public asset directory

### ISSUE THREAD

**Issue by michael4reynolds** [julienschmidt/httprouter#21]
I'm having difficulty implementing a wildcard route that handles all paths except the assets directory. 

```
r.Static("/public" , "./public")

r.GET("/*_", func(c *gin.Context) {...})
```

I'm getting _'panic: conflict with wildcard route'_

How can this be handled with httprouter?

**Comment by jbrodriguez** [comment]
@julienschmidt I browsed through the commits after this date, but didn't seem to find an option for this. Would you please provide some feedback.
Perhaps #4 , with `RedirectTrailingSlash` and `RedirectFixedPath` is the way to go ?
