### ISSUE TITLE
How to remove / in front of catch-all parameter?

### ISSUE THREAD

**Issue by yosualb** [julienschmidt/httprouter#222]
```
func Say(w http.ResponseWriter, r *http.Request, ps httprouter.Params) {
	fmt.Fprintf(w, "Say :%v", ps.ByName("everything"))
}

router := httprouter.New()
router.GET("/say/*everything", Say)
```

request: http://localhost/say/What%20Are%20You%20Doing%3F
response: Say :/What Are You Doing?

**Comment by yosualb** [comment]
I mean only using httprouter and without other library.

**Comment by rcorre** [comment]
Just ran into this. It seems like an odd design decision to include the leading `/` (especially since it only happens for catch-all parameters)

**Comment by rcorre** [comment]
Ah, [this](https://github.com/julienschmidt/httprouter/issues/77) is the reasoning

**Comment by blitzprog** [comment]
I am interested in this as well. The current behavior is counter-intuitive.

I understand the reasoning but I believe that when the `/` in the route has been written before the actual wildcard starting character `*` it should not be re-included in the wildcard match.
Is there an easy fix in the code for this which people could apply in a fork of the repository?

**Comment by tmthrgd** [comment]
What’s wrong with `strings.TrimPrefix(ps.ByName("name"), "/")`?

**Comment by blitzprog** [comment]
@tmthrgd 
A simple integer increment **only** in the case of `*` routes is much more efficient than a `strings.TrimPrefix` **call** on **every** single parameter retrieval just to achieve consistency, including `:` parameters (as a user of the lib, the parameter name alone doesn't tell you whether it was a `*` or `:` parameter, so the `ByName` wrapper wouldn't know whether it needs a `TrimPrefix` call or not).

**Comment by julienschmidt** [comment]
As @rcorre already figured out, here is the answer: https://github.com/julienschmidt/httprouter/issues/77#issuecomment-90640009

I know this is kinda counter-intuitive. Let's see if we can find a nicer way to deal with this in the future.
