### ISSUE TITLE
Pass a JSON parameter?

### ISSUE THREAD

**Issue by husseinfahmy** [julienschmidt/httprouter#224]
Hey, i can't seem to find any examples in the documentation or online of a JSON paratemeter being passed. I know if i simply pass more than 1 parameter it would format it into a json for me, but I'd rather craft the JSON on the front end and pass it as 1 parameter. Is that possible?

**Comment by julienschmidt** [comment]
If this is still relevant, please give an example. I don't quire understand your question. I think that is part of net/http and not httprouter.
