### ISSUE TITLE
Route priority impossible, unneccessary panic caused

### ISSUE THREAD

**Issue by Empty2k12** [julienschmidt/httprouter#231]
I am trying to implement something like this

domain.local/(:user/:trip/) -> INDEX (static file)
domain.local/data/:user/:trip -> DATA (generated JSON)

Basically the `domain.local/data/:user/:trip` should have a higher priority, which implies that no `:user` with the value `data` can exist.
Basically if the user browses to `domain.local/peter/test`, the index file should be served and routing is done in JS and if `domain.local/data/peter/test` is called GO should handle the request.

**Comment by dentych** [comment]
It's not a bug, it's a feature 👍 

In the README it states:

> **Only explicit matches:** With other routers, like http.ServeMux, a requested URL path could match multiple patterns. Therefore they have some awkward pattern priority rules, like longest match or first registered, first matched. By design of this router, a request can only match exactly one or no route.

**Comment by Empty2k12** [comment]
I ended up creating my own router that supports priority based routing and file serving.

**Comment by dentych** [comment]
Is it on Github for others to see, @Empty2k12 ? :)

**Comment by Empty2k12** [comment]
Nope, I guess I could OS it, but it's. nowhere as sophisticated as this one. I am doing SPAs that means I don't need any named entity extraction (aka. /:trip_numer or something) since that all happens in JavaScript

**Comment by dentych** [comment]
Sure, that's up to you.

I just like to see what others make in Go 😄
