### ISSUE TITLE
Router timeout

### ISSUE THREAD

**Issue by LeoCBS** [julienschmidt/httprouter#232]
Hi, i need some help to configure one timeout to router..

thanks!

**Comment by yegorch** [comment]
@LeoCBS Hi, you don't need to configure timeouts on router. 
Consult those guides for more details:
https://blog.cloudflare.com/the-complete-guide-to-golang-net-http-timeouts/
https://blog.cloudflare.com/exposing-go-on-the-internet/

**Comment by julienschmidt** [comment]
This package only provides routing for `net/http`. Timeouts and everything else should be configured there.
See also the links posted by @yegorch for further hints.
