### ISSUE TITLE
OPTIONS Allow header differs deterministically between OSes

### ISSUE THREAD

**Issue by tmornini** [julienschmidt/httprouter#248]
When setting ```HandleMethodNotAllowed``` to ```true```

# MacOS 10.13.6

```
HTTP/1.1 405 Method Not Allowed
Allow: GET, HEAD, OPTIONS
Content-Length: 19
Content-Type: text/plain; charset=utf-8
Date: ⧆⧆:date⧆
X-Content-Type-Options: nosniff
 
Method Not Allowed
```

# Ubuntu 16.04

```
HTTP/1.1 405 Method Not Allowed
Allow: HEAD, GET, OPTIONS
Content-Length: 19
Content-Type: text/plain; charset=utf-8
Date: ⧆⧆:date⧆
X-Content-Type-Options: nosniff
 
Method Not Allowed
```

This is causing us pain in testing using [http-spec](https://github.com/tmornini/http-spec) -- though we're aware that the headers are semantically equivalent.

**Comment by dolmen** [comment]
Is this about the order of the allowed methods in the `Allow` header?

**Comment by tmornini** [comment]
@dolmen Yes. Sorry for being less than 100% clear.
