### ISSUE TITLE
Disable directory listing with ServeFiles

### ISSUE THREAD

**Issue by emilgpa** [julienschmidt/httprouter#25]
Hi!,
When I use this ...

``` go
router.ServeFiles("/static/*filepath", http.Dir("/var/www/static"))
```

It works, but this show the directories, there are any way for disable the directory listing? (without insert a empty index.html in every dir)

**Comment by feyyazesat** [comment]
Hi, I solved this problem through http://stackoverflow.com/questions/13302020/rendering-css-in-a-go-web-application this answer. I'm a beginner and probably couldn't patch it for now. I did define funcs as in the answer.

type justFilesFilesystem struct {
	fs http.FileSystem
}

func (fs justFilesFilesystem) Open(name string) (http.File, error) {
	f, err := fs.fs.Open(name)
	if err != nil {
		return nil, err
	}
	return neuteredReaddirFile{f}, nil
}

type neuteredReaddirFile struct {
	http.File
}

func (f neuteredReaddirFile) Readdir(count int) ([]os.FileInfo, error) {
	return nil, nil
}

and before http.ListenAndServe


	fs := justFilesFilesystem{http.Dir(STATIC_FOLDER)}

	router.Handler("GET", "/static/*filepath", http.StripPrefix("/static", http.FileServer(fs)))

It works properly, no directory listing, and access js, cs etc. files.

**Comment by junhsieh** [comment]
I have added a middleware to disable directory listing:

```
package main

import (
        "log"
        "net/http"
        "strings"
)

import (
        "github.com/julienschmidt/httprouter"
)

const (
        gStaticDir = "static"
)

var (
        gMux *httprouter.Router
)

func main() {
        gMux = httprouter.New()

        // Serving the static files - use this if you would like to work with some middlewares.
        // NOTE: FileServer calls path.Clean() to clean up path.
        gMux.Handler("GET", "/"+gStaticDir+"/*filepath", NoDirListingHandler(http.StripPrefix("/"+gStaticDir+"/", http.FileServer(http.Dir(gStaticDir)))))

        srv := &http.Server{
                Handler: gMux,
                Addr:    ":8080",
        }

        if err := srv.ListenAndServe(); err != nil {
                log.Fatal("http.ListenAndServe: ", err)
        }
}

func NoDirListingHandler(h http.Handler) http.Handler {
        return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
                if strings.HasSuffix(r.URL.Path, "/") {
                        http.NotFound(w, r)
                        return
                }
                h.ServeHTTP(w, r)
        })
}
```

**Comment by gadelkareem** [comment]
There is a config option for this `DirectoryIndex = False`
