### ISSUE TITLE
Method Not Allowed - Post

### ISSUE THREAD

**Issue by eranya** [julienschmidt/httprouter#254]
Hi,

I am trying to mkae curl post on my local machine but getting Method Not Allowed error.
I followed all questions and answers with no luck.
I followed this example [https://github.com/julienschmidt/httprouter/issues/169](https://github.com/julienschmidt/httprouter/issues/169)
This is what I am doing:

    func getdd(w http.ResponseWriter, r *http.Request, _ httprouter.Params) {
       w.Header().Set("Access-Control-Allow-Methods", "POST, GET, OPTIONS, PUT, DELETE")
       w.Header().Set("Access-Control-Allow-Headers", "Content-Type, Content-Length, Accept-Encoding, X-CSRF-Token, Authorization, accept, origin, Cache-Control, X-Requested-With, X-MY-API-Version")
       w.Header().Set("Access-Control-Allow-Credentials", "true")
       w.Header().Set("Access-Control-Allow-Origin", "*")

       fmt.Fprint(w, "getdd!\n")
    }

    func main() {
       router := httprouter.New()
       router.POST("/getdd", getdd)
       log.Fatal(http.ListenAndServe("127.0.0.1:24266", router))
    }

I am placing this command:
curl http://127.0.0.1:24266   -X POST   -H 'Content-Type: application/json'   -H 'X-MY-API-Version: 1'   -d '{"command": "getdd", "text": ["123"]}'

I understand that I need to setup CORS prior launching the server. How do i do that using httprouter?
Thanks,

**Comment by julienschmidt** [comment]
Your only defined route is for `POST /getdd`, however you are requesting `POST /` with your curl command.
There is however a bug, as the router should however throw a `404 Not Found` error in this case.

**Comment by eranya** [comment]
The example was taken from Iota API reference [https://iota.readme.io/reference](https://iota.readme.io/reference). This works well with gin. 
What am I missing here?

Thanks

**Comment by julienschmidt** [comment]
It seems like their API doesn't use different URL paths to distinguish the different commands (everything is sent to the root `/`) but rather sends it within the JSON payload. In such a case httprouter is probably rather useless as you would just register 1 route (`router.POST("/", magicHandlerForEverything`)

**Comment by eranya** [comment]
Sorry but I didn't understand your response solution.
Can you show example please?

Thanks,

**Comment by eranya** [comment]
I see.
Thanks,
