### ISSUE TITLE
Parameter without value

### ISSUE THREAD

**Issue by YamilBracho** [julienschmidt/httprouter#255]
Hi, I have this route
MyServer/joining/states/:country
where country could be passed or not, so we have
MyServer/joining/states/:country/USA -- Get all states in USA
MyServer/joining/states/:country -- Get All states from all countries

However, when I specify my route without country I got 404
Is there a way to apply this route and then check if the parameter is present ?

TIA,
Yamil

**Comment by julienschmidt** [comment]
Isn't the route `/joining/states/` then exactly what you want? There is also no need to check if the parameter is empty or not then (I assumed that `MyServer` is a placeholder for your domain - if not: a good practice is to keep all routes lowercase).

The request path `/joining/states/USA` would match the route `/joining/states/:country`, if no is passed, the request path should be `/joining/states/` which matches the route `/joining/states/`.

**Comment by YamilBracho** [comment]
Thanks
Yes, I am using all lowercase routes...
What i want to use optional parameters ina  route. For example   
	router.GET("/joining/states/:cc", env.GetStatesFunc)
So I could do 
/joining/states/USA   --> Get all USA States
/joining/states/           --> All states from all countries
/joining/states/CAN    --> All Canada States

Regards,
Yamil

**Comment by julienschmidt** [comment]
Then an additional handler for the route `/joining/states/` is exactly what you want.

**Comment by YamilBracho** [comment]
Yes, I did that way...

Thanks a lot!!!
