### ISSUE TITLE
License text subtly deviates from 3-clause BSD license

### ISSUE THREAD

**Issue by matthijskooijman** [julienschmidt/httprouter#269]
The license used for this module seems to be the 3-clause BSD-license, except that it has some very small changes in the wording.

In particular, `Neither the name of the copyright holder nor the names of its contributors may be used` is replaced by `The names of the contributors may not be used` and`THE COPYRIGHT HOLDERS AND CONTRIBUTORS` is replaced by `JULIEN SCHMIDT`.

This change makes it harder or impossible for license scanning tools to recognize the applied license and requires manual review.

Is this deviation intentional? Would you consider changing to the standard BSD-3 text? IANAL, but I would think that the license itself does not really change, so making this change would probably be ok without getting consent from all contributors.

**Comment by julienschmidt** [comment]
Thanks, this was not intended.
I have no idea where I copied that license text from, but as far as I remember there were some kind of placeholders.
