### ISSUE TITLE
Option to pass parameters in request context.

### ISSUE THREAD

**Issue by bradleypeabody** [julienschmidt/httprouter#276]
From the README:
> The router itself implements the http.Handler interface. Moreover the router provides convenient adapters for http.Handlers and http.HandlerFuncs which allows them to be used as a httprouter.Handle when registering a route. The only disadvantage is, that no parameter values can be retrieved when a http.Handler or http.HandlerFunc is used, since there is no efficient way to pass the values with the existing function parameters. Therefore httprouter.Handle has a third function parameter.

It would seem that the request context (https://golang.org/pkg/net/http/#Request.Context) would be an excellent place to store these parameters without breaking the http.Handler contract.  Some design decisions would need to be made as to how exactly to store these params in there and I can probably help a lot with both design and implementation if this something that you would consider merging into the project.  It could be an option and would not break existing usage.

Motivation: There are a lot of Go routers and muxers out there and unfortunately it's very common to see library-specific structs and function calls creep into otherwise clean and muxer-independent handler code.  If I want to write a handler that is meant to be used by other developers with their choice of muxer, this is almost impossible to do without writing support for each individual muxer (httprouter, Gorilla, Goja, Gin, etc, etc. - they all want me to import their own stuff for even the simplest functionality).  The result is I cannot just write a handler and leave the choice of muxer up to the application developer integrating it in.   By providing a way to support basic functionality including path params using just the http.Handler interface, it would mean httprouter gains even more facility by not forcing handlers to import it.  It would also incidentally mean that people like me trying to write reusable handlers could talk about how cool httprouter is that they don't require vendor lock-in for basic functionality.

Let me know what you think of this.  I would be happy to propose some more specifics with some options on how the parameters could be encoded into into the context.

**Comment by bradleypeabody** [comment]
Right after I wrote the above I noticed this file https://github.com/julienschmidt/httprouter/blob/master/params_go17.go

Which is very close to what I describe above, but it still requires the caller to import and rely on httprouter.Params.

What about making a ParamsContext which implements Context by delegating all calls to a parent context, but also answering Value() calls for a Params ([]Param).  I.e. given route "/someplace/:name" handlers could do simply `r.Context().Value("name")`?

**Comment by julienschmidt** [comment]
Params in Context support was added in #147

See [Why doesn't this work with http.Handler?](https://github.com/julienschmidt/httprouter#why-doesnt-this-work-with-httphandler). You can easily make a local alias of that helper function / make your own function to retrieve the params from the context without importing HttpRouter in every file.
