### ISSUE TITLE
dynamic/wildcard subdomains.

### ISSUE THREAD

**Issue by wahello** [julienschmidt/httprouter#277]
#### how to set for dynamic/wildcard subdomains? Like [mux](https://github.com/gorilla/mux#matching-routes) wildcard subdomain.

**Comment by julienschmidt** [comment]
HttpRouter only provides path matching.
See [README: Multi-domain / Sub-domains](https://github.com/julienschmidt/httprouter#multi-domain--sub-domains). For dynamic subdomains I'd start by splitting the host at the required '.'. If you want to use a common router but pass the value to the handler, you could store it in the request context.

If you want to combine static and wildcard domains, you can use a map and if the the host can not be found in there continue with the logic for the dynamic subdomains.
