### ISSUE TITLE
Thinking about Contributing to httprouter as My Graduation Project

### ISSUE THREAD

**Issue by BruceWangNo1** [julienschmidt/httprouter#282]
Hi, my name is Yong Wang. And I am a graduate student from Sun Yat-sen University, China. Please excuse me for posting non-technical problems on Github Issues. I am about to graduate in June next year. So I have to work on my graduation project pretty soon. Some of my friends have already started. My supervisor is pretty open to what project I am into. I am proficient at Go. And I have a fair amount of working knowledge of API gateway from the github.com/fagongzi/gateway project when I was doing an internship at Tencent Games. I am looking to work on an open-source project where my work could eventually be concluded as my graduation thesis. I noticed that httprouter uses a compressing dynamic trie structure for efficient matching. And there are very good benchmarks. There is one requirement which is that my work on the graduation project needs to have at least two novel approaches to some problems. Is it feasible? If so, would you please suggest some problems that I can work on?

Looking forward to your replies. Any feedbacks are welcome.

Sincerely,
Yong

**Comment by julienschmidt** [comment]
I don't have any suggestions, but I hope your graduation project is going well :)

**Comment by BruceWangNo1** [comment]
Thanks
