### ISSUE TITLE
405 Method Not Allowed

### ISSUE THREAD

**Issue by claudiofelber** [julienschmidt/httprouter#30]
Hi Julien

The router currently returns 404 Not Found even if the path (and thus the resource) exists but the request method does not match. In such a situation, to be a good HTTP citizen, it should return 405 Method Not Allowed and indicate the available methods for the desired resource in the "Allow" header.

I've looked into your router implementation. The way the routes are currently organized, doing this wouldn't be that easy (and fast) because you have a separate tree for each request method. I think you should have one tree instead and store the defined methods along with their handlers in the node structure.

To customize the server response, in addition to the NotFound handler to be found in the Router structure, there should also be a MethodNotAllowed handler. It should be passed a list of allowed methods.

Regards,
Claudio

**Comment by ydnar** [comment]
The current implementation returns 405 for all requests if there’s a more general (e.g. wildcard) route for another method, e.g.:

```go
r.Handle("GET", "/v1/search", search)
r.Handle("OPTIONS", "/*path", handler)
```

GET requests for `/v1/search` will **always** return a 405 with this change.

**Comment by julienschmidt** [comment]
#51 was now reverted (#52).
