### ISSUE TITLE
Why ((missing)) appears for the content received by the post method

### ISSUE THREAD

**Issue by wuknet** [julienschmidt/httprouter#302]
Why ((missing)) appears for the content received by the post method
为什么 POST方法接收的内容，出现了((MISSING))!
I use post to receive the content submitted by the form form. As long as the symbol% appears, it will appear%!; (missing)
我用POST方式接收form表单提交的内容，只要出现%这个符号，就会出现 %!;(MISSING)

下面是接收表单的函数
Here is the function to receive the form
```
func Get_str(r *http.Request, varname string) string {
	// 解析客户端请求的信息
	if err := r.ParseForm(); err != nil {
		return ""
	}
	revar := r.Form.Get(varname)
	revar = html.EscapeString(revar)
	return revar
}
```
有谁知道原因，谢谢了。
Who knows why? Thank you.

**Comment by razonyang** [comment]
I guessed that it isn't an issue of `Get_str`, the problem seems to come from functions like `fmt.Printf`, `fmt.Sprintf`, `printf` (template) . Please chekc your code.

我想这不是 `Get_str` 的问题，问题似乎来源于类似 `fmt.Printf`、`fmt.Sprintf`、`printf` (模板)  的函数。请检查你的代码。

**Comment by wuknet** [comment]
Thank you. I used FMT. Fprintf (W, revar) to print the contents of the received variables directly. As long as the sign% appears,%!; (missing)

谢谢，我是直接用fmt.Fprintf(w,revar) 直接打印 接收的变量内容。只要出现%这个符号，就会出现 %!;(MISSING)

这样写接收
Write like this receive

intro0 := Get_str(r, "intro0")
fmt.Fprintf(w,intro0)

这样提交
Such submission

<form action="/save" method="post">
<textarea name="intro0"></textarea>
<input type="submit" value=" ok " />
</form>

我问了好多人找不到原因
I asked a lot of people why they couldn't find it

**Comment by wuknet** [comment]
存在数据库中是 style=&#34;width:95%;&#34;   通过打印 fmt.Fprintf(w,intro0)  变成 style="width:95%!;(MISSING)"

In the existing database, style = &ා34; width: 95%; &ා34; by printing fmt.fprintf (W, intro0), it becomes style = "width: 95%!; (missing)"

如何解决呀
How to solve it

**Comment by razonyang** [comment]
Yes, `fmt.Fprintf(w,intro0)` causes this problems, you should take a look of [fmt](https://golang.org/pkg/fmt/) document. Use `io.WriteString(w, intro0)`(recommended), `fmt.Fprint(w,intro0)` or `fmt.Fprintln(w,intro0)` instead.

 `fmt.Fprintf(w,intro0)` 是原因所在，因为intro0作为format参数，如果出现`%*`，它会作为verbs，但缺少后续参数，所以才会出现 missing，你应该看下 [fmt](https://golang.org/pkg/fmt/) 文档。可以使用`io.WriteString(w, intro0)`(推荐), `fmt.Fprint(w,intro0)` 或者 `fmt.Fprintln(w,intro0)` 代替。

**Comment by wuknet** [comment]
谢谢，你让我理解了更多的内容。我还想了解下，作为web输出，就是html输出，Golang哪个函数或做法才标准，或者才合理。或有什么推荐。
Thank you for letting me understand more. I also want to know which function or practice of golang is standard or reasonable as web output, namely HTML output. Or any recommendations.

**Comment by razonyang** [comment]
Package [`html/template`](https://golang.org/pkg/html/template/) is what you want.
Btw, close issue if it was sloved, and stackoverflow is a better place to ask questions, since it is not an issue of `httprouter`.

可以使用  [`html/template`](https://golang.org/pkg/html/template/) 包。另外，如果解决了请关闭这个问题，你可以去stackoverflow提问，因为这并不是httprouter的问题。

**Comment by wuknet** [comment]
非常感谢
