### ISSUE TITLE
TLS Cert Authentication for Handle

### ISSUE THREAD

**Issue by dhcgn** [julienschmidt/httprouter#316]
How to use a TLS Cert Authentication for one handle?
I managed this only as a global configuration with `http.DefaultTransport`.

```
transport := &http.Transport{
	TLSClientConfig: &tls.Config{
		Certificates: []tls.Certificate{cert},
	},
}

http.DefaultTransport = transport
```

**Comment by julienschmidt** [comment]
TLS authentication happens before the first HTTP packet is sent. Thus per-handle TLS Auth is not possible (as the request path is not yet known then). You could use a different port and probably also build a solution using a different (sub-)domain. The server name (domain) IS known during TLS Auth.

**Comment by dhcgn** [comment]
Thanks for your feedback, I wrote a question on stackoverflow, how to use TLS/SSL Client Authentication for specific hosts, see https://stackoverflow.com/q/63213638/1776231.
