### ISSUE TITLE
Ever considered Github Sponsorships?

### ISSUE THREAD

**Issue by eacp** [julienschmidt/httprouter#327]
IDK if this is an issue with the library itself, but this is one of the most widley loved libraries by the gophers, and I amd sure
Github sponsorships would definitely help.

**Comment by ZetiMente** [comment]
@eacp I have been trying to decide between this repo and the gorilla mux. I was pretty interested reading the performance and memory usage of this repo but it worries me that there isn't any active development in over a year. Is the repo still workable with the newest versions of Go?

**Comment by julienschmidt** [comment]
Thank you very much for the suggestion and the kind words.
I learned a lot implementing this library and the way it is received and used by the Go community is really the best return for the time that I invested into this project that I could wish for ❤️ 

Nowadays the bottleneck really is time, not monetary incentive. If you like the package, use it and spread the word about it. If you can devote time, help making the Go ecosystem even better. Either by working on this project, or even better by pushing new projects to the next level.
