### ISSUE TITLE
Fails with "embed" package

### ISSUE THREAD

**Issue by pnsvk** [julienschmidt/httprouter#354]
An adaptation of the following snippet for httprouter fails with multiple attempts.

```
import (
    "embed"
    "io/fs"
    "net/http"
)

//go:embed public
var content embed.FS

func handler() http.Handler {

    fsys := fs.FS(content)
    html, _ := fs.Sub(fsys, "public")

    return http.FileServer(http.FS(html))
}

func main() {

    mux := http.NewServeMux()
    mux.Handle("/", handler())

    http.ListenAndServe(":8080", mux)
}
```

Can you please share a working snippet with httprouter ? or is it even feasible..

**Comment by Sijisu** [comment]
This works no problem for me:

```golang

//go:embed static
var content embed.FS

mux := httprouter.New()

if static, err := fs.Sub(content, "static"); err == nil {
    mux.Handler("GET", "/static/*path", http.StripPrefix("/static", http.FileServer(http.FS(static))))
} else {
    panic(err)
}

http.ListenAndServe(":8080", mux)
```

Would be helpful if you could next time share exactly what are you trying to do **and how** :)

**Comment by rynhndrcksn** [comment]
To anyone who finds themselves here, and you, like me, were trying to figure out how to use `http.FileServerFS` to serve your embedded files with httprouter, the following snippet works:

```go
router := httprouter.New()
router.Handler(http.MethodGet, "/static/*path", http.FileServerFS(ui.Files))
```

Thank you @Sijisu! without seeing your example, I wouldn't have realized I was missing the `*path` portion of the route.

**Comment by vituchon** [comment]
Thanks guys... @rynhndrcksn may I ask from where the definition `ui.Files` comes from?

**Comment by rynhndrcksn** [comment]
@vituchon It comes from a `ui` directory in my project. The layout of this directory is the following:

- `ui/`
  - `html/` - contains all my `.tmpl` files.
  - `static/` - contains all my CSS/JS/Images.
  - `efs.go` - embeds the `html/` and `static/` directories when the binary is built.

If you're curious, the contents of `efs.go` is below:

```go
package ui

import "embed"

//go:embed "html" "static"
var Files embed.FS
```
