### ISSUE TITLE
Serve Static Files from Root

### ISSUE THREAD

**Issue by phillipCouto** [julienschmidt/httprouter#4]
I tried searching the documentation for an explaination on how to server static content from "/". In my application design all of the API uses /api/\* all paths outside the api folder are considered static content.

Is there a current way of handling this in httprouter?

**Comment by hit9** [comment]
For now, I'm on go 1.5.2, the solution is (without the `ServeHTTP`
```
router.NotFound = http.FileServer(http.Dir("web/"))
```

**Comment by cooervo** [comment]
@phillipCouto please post the complete main.go of how you solved this, it seems like what you did is a hack has it actually worked in production?
