### ISSUE TITLE
Routes ending with format extension (e.g. `.js`)

### ISSUE THREAD

**Issue by dolzenko** [julienschmidt/httprouter#42]
Trying to setup routes like `/storage/:name.js` makes httprouter think parameter name is `:name.js` instead of (desired) `:name`. Is there a way around it or is that by design?

**Comment by philipgiuliani** [comment]
There is still no way in 2016, or?

**Comment by Annonomus-Penguin** [comment]
A way around it, although not as clean, you can always check the extension in the handler. Again, not as handy, but it's doable.
