### ISSUE TITLE
Discussion: 405 Support breaks wildcard routes

### ISSUE THREAD

**Issue by julienschmidt** [julienschmidt/httprouter#52]
As reported by @ydnar in #51, the 405 Support introduced in #51 breaks wildcard routes:
> This completely breaks wildcard routes for alternate methods, for example:
>
> r.Handle("GET", "/v1/search", search)
> r.Handle("OPTIONS", "/*path", handler)
> GET requests for /v1/search will always return a 405 with this change.

**Comment by javierprovecho** [comment]
Excuse me @julienschmidt , but I can't replicate that bad behaviour, even changing the order of the handlers. Here is my code:

```go
package main

import (
	"fmt"
	"github.com/julienschmidt/httprouter"
	"log"
	"net/http"
)

func Index(w http.ResponseWriter, r *http.Request, _ httprouter.Params) {
	fmt.Fprint(w, "Welcome!\n")
}

func Hello(w http.ResponseWriter, r *http.Request, ps httprouter.Params) {
	fmt.Fprintf(w, "hello, %s!\n", ps.ByName("name"))
}

func main() {
	router := httprouter.New()
	router.Handle("OPTIONS", "/*name", Hello)
	router.Handle("GET", "/v1/search", Index)
	log.Fatal(http.ListenAndServe(":8080", router))
}
```
And here the request I made to try it:
```bash
$ curl -X OPTIONS localhost:8080/mynameisjavier
hello, /mynameisjavier!

$ curl localhost:8080/mynameisjavier
405 method not allowed

$ curl localhost:8080/v1/search
Welcome!

$ curl -X OPTIONS localhost:8080/v1/search
hello, /v1/search!

$ curl -X POST localhost:8080/v1/search
405 method not allowed
```
Thank you in advance for your response.

**Comment by ydnar** [comment]
Morning... I'll send an example (or a test)  that illustrates the bug. 

Randy

**Comment by julienschmidt** [comment]
... or just add an option to turn the 405 handling off.

The abuse of the NotFound handler to chain the router is not really intended and probably not a really common use case. But of course it is not my intention to make this use-case impossible.

**Comment by julienschmidt** [comment]
No comments?
I'd like to reintroduce the 405 support soon again.

**Comment by javierprovecho** [comment]
No comments from me actually because I had two hard weeks at university.


Your solution of turning on/off 405 method looks nice.




I'll try to push a new pull request soon.




As always, I'm reading your mails, but sometimes I'm not able to respond quickly.


—
Enviado desde Mailbox
