### ISSUE TITLE
Panic on Handle /:foo:bar

### ISSUE THREAD

**Issue by rogpeppe** [julienschmidt/httprouter#56]
The following program panics with "slice bounds out of range" error. This
case should be caught and a more understandable message issued instead.

	package main
	
	import (
		"github.com/julienschmidt/httprouter"
		"net/http"
	)
	
	func main() {
		r := httprouter.New()
		r.Handle("GET", "/:foo:bar/oops", func(http.ResponseWriter, *http.Request, httprouter.Params) {})
	}

The panic is as follows:

	panic: runtime error: slice bounds out of range

	goroutine 1 [running]:
	github.com/julienschmidt/httprouter.(*node).insertChild(0xc20805c120, 0x1, 0x6bd190, 0xe, 0x72ea70)
		/home/rog/src/go/src/github.com/julienschmidt/httprouter/tree.go:217 +0x57a
	github.com/julienschmidt/httprouter.(*node).addRoute(0xc20805c060, 0x6bd190, 0xe, 0x72ea70)
		/home/rog/src/go/src/github.com/julienschmidt/httprouter/tree.go:184 +0xac
	github.com/julienschmidt/httprouter.(*Router).Handle(0xc208030f70, 0x6af1d0, 0x3, 0x6bd190, 0xe, 0x72ea70)
		/home/rog/src/go/src/github.com/julienschmidt/httprouter/router.go:219 +0x1ae
	main.main()
		/home/rog/src/tst.go:10 +0x9a

**Comment by julienschmidt** [comment]
Even worse: `/:foo:bar` currently works without panicking at all and the router creates nodes for both `:foo:bar` and `:bar`!
I'm working on a fix.
