### ISSUE TITLE
Google App Engine (GAE)

### ISSUE THREAD

**Issue by fnkr** [julienschmidt/httprouter#58]
Hello,

how can I use this together with Google App Engine?
Here is a working example that uses the `net/http` library:
```go
package main

import (
    "fmt"
    "net/http"
)

func init() {
    http.HandleFunc("/", index)
}

func index(w http.ResponseWriter, r *http.Request) {
    fmt.Fprint(w, "Hello, world!")
}
```

I tried to do the same with `httprouter`:
```go
package main

import (
	"fmt"
	"net/http"
	"github.com/julienschmidt/httprouter"
)

func init() {
	router := httprouter.New()
	router.GET("/", index)
}

func index(w http.ResponseWriter, r *http.Request, _ httprouter.Params) {
	fmt.Fprint(w, "Hello, world!")
}
```

But it doesnt work. I always get `404 page not found`.

**Comment by julienschmidt** [comment]
You somehow have to tell AppEngine to use this router.
I'm not an AppEngine user, but AFAIK the recommended way to do this is by adding `http.Handle("/", router)` to the end of `init()`

**Comment by fnkr** [comment]
Thanks, that works.

```go
package main

import (
    "fmt"
    "net/http"
    "github.com/julienschmidt/httprouter"
)

func init() {
    router := httprouter.New()
    router.GET("/", index)
    http.Handle("/", router)
}

func index(w http.ResponseWriter, r *http.Request, _ httprouter.Params) {
    fmt.Fprint(w, "Hello, world!")
}
```

**Comment by chakrit** [comment]
Just in case everyone encounters this, I'm a GAE user. It doesn't do anything special to your app besides forwarding requests. So you can setup any HTTP listener normally and you should be good to go.

**Comment by sutanto1010** [comment]
Nice, thank you :+1:

**Comment by sampalm** [comment]
Thanks 👍

**Comment by mariaefi29** [comment]
Hello,

Could you please tell what should I write if I have multiple urls? I get 404 error always:( Now I have this:

```
func main() {
	router := httprouter.New()
	router.GET("/", index)
	router.POST("/subscribe", subscribe)
	router.GET("/posts/show/:id", show)
	router.POST("/posts/show/:id", like)
	router.POST("/posts/show/:id/comments", comment)
	router.GET("/about", about)
	router.GET("/category/:category", category)
	router.GET("/contact", contact)
	router.POST("/contact", sendMessage)
	router.ServeFiles("/static/*filepath", http.Dir("public"))
	// log.Fatal(http.ListenAndServe(":8080", router))
	appengine.Main()
}
```

And I always get 404 status. I've tried putting everything in the init() function, but it didn't help.

I wold be very grateful for your help.

**Comment by mariaefi29** [comment]
Thank you so much!
