### ISSUE TITLE
Handle method to accept all HTTP methods

### ISSUE THREAD

**Issue by niwaywood** [julienschmidt/httprouter#66]
Unless I'm missing something, currently the handle method (http://godoc.org/github.com/julienschmidt/httprouter#Router.Handle) can only handle a single HTTP method (e.g. GET, POST etc).

It would be great if we could do something like `router.Handle("ALL", "/", myHandler)` and then have a `switch` statement within `myHandler` for each HTTP method

**Comment by julienschmidt** [comment]
Yes, and this is intended. one of the goals of this router is to only match the routes (and methods) which are intended.
If you still want the behavior above (not recommended), I would suggest to use a helper function which registers the route for all the methods you want.

**Comment by caibirdme** [comment]
Our application is like a reverse proxy, but with some APIs to get its inner information. So what I want is something like:
```
r.HandleALL("/proxy/*upstream", doReverseProxy)
r.Get("/foo", bar)
```
But it's not very convenient for that
