### ISSUE TITLE
How to serve static files from ./public dir to the root path?

### ISSUE THREAD

**Issue by amrnt** [julienschmidt/httprouter#7]
I tried the following, but it didn't work

``` go
  router.ServeFiles("/*filepath", http.Dir("public/"))
// or
  http.Handle("/", http.FileServer(http.Dir("public/")))
```

**Comment by daveroberts** [comment]
> [using the NotFound handler to serve files] is not a good idea in my opinion

Why not?  I need the ability to server index.html and favicon files from my root, and I'm looking for the best way to accomplish this.

**Comment by deboerr** [comment]
I agree with daveroberts ... ALL root folders on web sites that I develop for my customers contain 1 file (index.html) and various subfolders (eg /static, /api)
Using Juliens  great router component, I can serve a file from any and all subfolders ... however I cannot serve index.html with it.
Advice anyone please ??

**Comment by CodeNameWoods** [comment]
The way I solved index problem was to serve index .html like this:

`
func Index(w http.ResponseWriter, r *http.Request, _ httprouter.Params) {
  http.ServeFile(w, r, r.URL.Path[1:])
}

func main() {
  router := httprouter.New()
  router.GET("/", Index)
  router.ServeFiles("/app/*filepath", http.Dir("static"))
  ....
  log.Fatal(http.ListenAndServe(":8080", router))
}
`

**Comment by daveroberts** [comment]
This forces all of your static files to be accessible under /static.  This may work for some projects, but not all.  A couple of examples which come to mind:

- The default path for a favicon is in the root directory.  If a user requests a non-HTML page, the favicon won't load
- People may already be linking to files on your site and you can't change the links

**Comment by ScaryWolfMan** [comment]
What is the best way to wrap the router.ServeFiles in a middleware in case I want to protect some assets?

**Comment by cooervo** [comment]
This is what finally worked for me:
```
func main() {
	router := httprouter.New()
	router.GET("/", LandingPage)
	router.GET("/Create", Create)
	router.ServeFiles("/static/*filepath",http.Dir("static"))
	logger.LogInfo("Server running at http://0.0.0.0:3001")
	log.Fatal(http.ListenAndServe(":3001", router))
}
```

**Comment by tehsphinx** [comment]
@julienschmidt 
I keep running into this issue again and again when trying to convert an existing php/python/vb6/etc. website to go. I love your router but It is not usable for all these websites because the static files never are to be served in a separate path. I would like them to have a separate path but it just isn't actionable to change that for these large projects.

**Comment by tehsphinx** [comment]
Solved it with 2 separate routers and the `NotFound` handler. That way I can check for specific routes first and if none of them match serve static files.

```
	router := httprouter.New()
	router.GET("/", s.index())
	router.GET("/api/", s.api())

	// if not found look for a static file
	static := httprouter.New()
	static.ServeFiles("/*filepath", http.Dir(staticPath))
	router.NotFound = static
```

**Comment by DylanVerstraete** [comment]
Solved it without creating a new router while serving all static files under `/`

`router.NotFound = http.FileServer(http.Dir(staticPath)).ServeHTTP`
