### ISSUE TITLE
Wildcard routing

### ISSUE THREAD

**Issue by jasonrichardsmith** [julienschmidt/httprouter#70]
Hello,

I am porting an application where all traffic gets sent to the same index.html, regardless of path except the API endpoint.  AngularJS is responsible for building the page.  Go will work as the API that will tell Angular how the page is served.

http://mongular.org/

Essentially I need all traffic aside from anything under the 'foo.com/mongolar' (this is configurable) to be routed to one index.html.

I am having problem with the wildcard route.  Is this doable with your router?

I am also serving some js and css as static files from their own folders.

**Comment by jasonrichardsmith** [comment]
This is where I am at with the code at this point.
https://github.com/jasonrichardsmith/mongolar/blob/master/mongolar.go

**Comment by julienschmidt** [comment]
If I understand you correctly, you have something like the following structure:
```
/mongolar/... [a lot of API routes]
/css/*filepath
/js/*filepath
/index.html
```
I think there are two options:
1) Use [Router.NotFound](http://godoc.org/github.com/julienschmidt/httprouter#Router.NotFound) handler to send everything to index.html when there is no defined route
2) Use HttpRouter only for the API under `/mongolar` and use the default http.Mux for handling the css, js folders, as well as the dispatching to HttpRouter and sending all the rest to the index.html

**Comment by jasonrichardsmith** [comment]
Yes, I see that now.  Thank you!
