### ISSUE TITLE
Return default all routes - HTTP Method

### ISSUE THREAD

**Issue by johnidm** [julienschmidt/httprouter#75]
Hey,

I need to map all routes invoked with method HTTP OPTIONS and return a default status.

I tried this:
```
router := httprouter.New()
router.OPTIONS("/", DefaultRoute)
...
...
...
func DefaultRoute(w http.ResponseWriter, r *http.Request, _ httprouter.Params) {

	if !utils.APIKeyIsValid(w, r) {
		return
	}

	w.WriteHeader(http.StatusOK)
}
```
But return this error:

```
panic: wildcards must be named with a non-empty name
```

Is there anything I can do to resolve this problem.

Thanks.

**Comment by julienschmidt** [comment]
Like the error message says, you have to give the wildcard parameter a name: `router.OPTIONS("/*whatever", DefaultRoute)`
