### ISSUE TITLE
 Go CORS handler as a middleware in HttpRouter

### ISSUE THREAD

**Issue by johnidm** [julienschmidt/httprouter#76]
Hey 

I need to use [Go CORS handler](https://github.com/rs/cors) with httprouter, but both use the same parameter in the `http.ListenAndServe` function .

See:

Go CORS handler
```
handler := cors.Default().Handler(h)
http.ListenAndServe(":8080", handler)
```
HttpRouter
```
router := httprouter.New()
router.GET("/", Index)
http.ListenAndServe(":8080", router)
```

Can be used Go CORS handler as a middleware in HttpRouter?

Thanks

**Comment by julienschmidt** [comment]
Looking at the examples of Go CORS handler, probably just something like the following?
```go
router := httprouter.New()
router.GET("/", Index)

handler := cors.Default().Handler(router)
http.ListenAndServe(":8080", handler)
```

**Comment by johnidm** [comment]
I tried this, but it doesn't work:

```
router.GET("/newslatters", GetNewslatters)
router.DELETE("/newslatter/:id", DeleteNewslatter)

c := cors.New(cors.Options{
   	AllowedOrigins: []string{"*"},
       AllowedMethods: []string{"GET", "POST", "DELETE", "PUT", "OPTIONS"},
})

log.Fatal(http.ListenAndServe(":"+*port, c.Handler(router)))
```

**Comment by julienschmidt** [comment]
What doesn't work? Compile error? Missing headers?

**Comment by nickveenhof** [comment]
I can actually confirm this does work.

	// Add CORS support (Cross Origin Resource Sharing)
	handler := cors.Default().Handler(router)
	err = http.ListenAndServe(":"+conf.BindPort, handler)
	if err != nil {
		logger.Fatal(err)
	}

**Comment by arekkas** [comment]
I can confirm this issue, please reopen it.

**Comment by rs** [comment]
`cors` lib author here. Please tell us what is not working. If you don't see the CORS headers using curl, make sure you send the `Origin` header within your request.

**Comment by arekkas** [comment]
Sorry, i thought I deleted my comment as I was mistaken :)
