### ISSUE TITLE
Catch-all parameter value has a leading slash

### ISSUE THREAD

**Issue by bruth** [julienschmidt/httprouter#77]
I used a catch-all parameter and noticed that the value returned from `p.ByName("foo")` has a leading slash. Is this intentional? If so, what is the reasoning?

**Comment by julienschmidt** [comment]
Yes, it is intended since the catch-all also matches the previous root. Eg. `/blah/*filepath` also matches `/blah/` (while `/blah/:filepath` would not).

**Comment by bruth** [comment]
I see, thank you for the clarification.
