### ISSUE TITLE
Connection : close on websocket upgrade from browser

### ISSUE THREAD

**Issue by rhacker** [julienschmidt/httprouter#82]
This is the first time I try to implement websocket and httprouter. But the weird thing I see is, the `Connection` header is changed to `close` in `ServeHTTP` in httprouter ( I print out all header in https://github.com/julienschmidt/httprouter/blob/master/router.go#L291 with `fmt.Printf("%v", req.Header)` ). Meanwhile the Header being sent from Chrome is clearly `upgrade` which is required for websocket lib to upgrade the HTTP to ws protocol.
I don't know what makes the change, and why it changes.

Thanks

**Comment by rhacker** [comment]
Sorry, it doesn't seem to be the problem of httprouter.

**Comment by hunter-christopher** [comment]
Did you find a way to implement a websocket using httprouter?

**Comment by Bruce-sz** [comment]
Did you find a way to implement a websocket using httprouter? 
@hunteramericano 👍 ,have you find the way? tks!

**Comment by julienschmidt** [comment]
What library do you intend to use for WebSockets? Basicially it just requires to register a handler e.g. at /websockets that handles the protocol upgrade.
