### ISSUE TITLE
Tags / Releases

### ISSUE THREAD

**Issue by ChristopherRabotin** [julienschmidt/httprouter#83]
Would it be possible to have tags on the repo to ease management of dependencies? Currently, the solution is to use the commit number and keep track of changes. With tags or releases, it would be easier to either see all the commits since a given tag, or even to write up release notes.

Thanks.

**Comment by TheTincho** [comment]
Hey,

Are you planning to continue doing releases? I see many commits since the last one, so I am not sure if those are still current...

**Comment by julienschmidt** [comment]
See #189
