### ISSUE TITLE
Parse query parameter /hello?name=username

### ISSUE THREAD

**Issue by abhijitkadam** [julienschmidt/httprouter#9]
I am not sure email for help is mentioned or there is a mailing list for this project.

How do parse query parameter? Like I have /hello?name=abhijit the for this pattern I should get "abhijit" when I read from ps.ByName("name"), however unable to read

**Comment by b35li** [comment]
@julienschmidt 
How to write the router? the followed code does NOT work??
<code
trouter.GET("/hello?name=xxx", Hello)
</code>

**Comment by julienschmidt** [comment]
`router.GET("/hello", Hello)`, then use 
```go
func Hello(w http.ResponseWriter, r *http.Request, ps httprouter.Params) {
    queryValues := r.URL.Query()
    fmt.Fprintf(w, "hello, %s!\n", queryValues.Get("name"))
}
```
The URL query is NOT part of the URL path. The router only matches against the request method and the path.

**Comment by b35li** [comment]
Thanks for quick response. Gratitude.

But after looking through the README and testing, the router should go like this 
<code>
router.GET("/hello/*filepath", Hello)
</code>

then to parse the URL. It works.

**Comment by preetamyadav** [comment]
http://localhost:8080/api/v1/itineraries/all?auth-token=KeQEtE8VI3duSqXHnrDoFKMeilRfmE&auth-email=melissajwolff+testabc@gmail.com

when i tried to get 

v := r.URL.Query()

it omittted the + sign from email .

**Comment by julienschmidt** [comment]
@preetamyadav Just must [query-escape](https://golang.org/pkg/net/url/#QueryEscape) values first before using them in an URL query. `+` is used to escape spaces: https://play.golang.org/p/2o1jCP3Ut7

**Comment by preetamyadav** [comment]
Thanks @julienschmidt

**Comment by 88SergiiOliinyk** [comment]
POST https://{notificationUrl}?validationToken={token} 

 r.URL.Query() - empty. Works only for Get method  ((
