### ISSUE TITLE
Can't set a handler for NotFound

### ISSUE THREAD

**Issue by Skarlso** [julienschmidt/httprouter#93]
Hi!

Sorry, I'm a bit new to this. I'm trying to set NotFound to a custom handler as you are writing to be able to serve a static not found page. It's very simple, I'm doing what you wrote in the README.md.

This is my code => 

```go
	r.NotFound = http.FileServer(http.Dir("assets/index.html")).ServeHTTP
```

And this is the error I'm getting: 

```
cannot use http.FileServer(http.Dir("assets/index.html")).ServeHTTP (type func(http.ResponseWriter, *http.Request)) as type http.Handler in assignment: func(http.ResponseWriter, *http.Request) does not implement http.Handler (missing ServeHTTP method)
```

Any clue as to why this is happening?

Thanks!
Skarlso

**Comment by JamesOwenHall** [comment]
This is what you want:

```go
r.NotFound = http.FileServer(http.Dir("assets/index.html"))
```

`r.NotFound` is of type `http.Handler`, which is an interface for any type that satisfies the `ServeHTTP` method.  `http.FileServer` returns a handler.  But you were trying to use the `ServeHTTP` function itself as the handler.

**Comment by fnkr** [comment]
@JamesOwenHall What if I want to run a function instead of serving static files?

I had this before, but it does not work with the anymore :-(
```go
func error404Handler(w http.ResponseWriter, r *http.Request) {
	...
}
```

**Comment by JamesOwenHall** [comment]
I think you're mixing up the `http.Handler

**Comment by Skarlso** [comment]
Sorry for posting so late!!! I'm terribly sorry. 

So, no, that won't work. I'm trying this => 
```go
r.NotFound = http.FileServer(http.Dir("assets/index.html"))
```
But that, if I call it like this: 
```
http://localhost:8484/asdf
```
It will only display this: 
```
404 page not found
```
Which means it did not pick up on the 404 page under assets/index.html which it should display if I understand this correctly, no?

**Comment by julienschmidt** [comment]
Try
```go
r.NotFound = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
    http.ServeFile(w, "assets/index.html")
}))
```
instead.

`"assets/index.html"` is not a directory path. It probably tries to serve something like assets/index.html/asdf then.

**Comment by Thomasdezeeuw** [comment]
You're trying to serve a directory called 'assets/index.html' with that call. So requesting '/asdf' will result in trying to read 'assets/index.html/asdf', which won't be found. And thus returns its default 404 page.

Want you want is:http://golang.org/pkg/net/http/#ServeFile. This serves a single file.

**Comment by Skarlso** [comment]
Damn.... Yeah. @julienschmidt with the slight addition that you need to pass in the request as well. 

Thanks guys, I was being stupid. Well, first time I'm using things like this in go. Thanks for the long way, sorry, I'm closing this immediately.
