### ISSUE TITLE
Handle arrays in path /resource/id/:[id]

### ISSUE THREAD

**Issue by panamafrancis** [julienschmidt/httprouter#95]
It would be very useful for the following to be valid

    r.GET("/resource/id/:id", GetSingleResource)     
    r.GET("/resource/id/:[id]", GetMultiResource)  

I think this is part of the HTTP 1.1 spec... not sure

I don't think it's necessary for httprouter to parse the array into a []string

I'd be happy to do it... just let me know your thoughts before i crack on.

**Comment by julienschmidt** [comment]
I'm not sure what you mean by `:[id]`. What value would match `:[id]` and what `:id`?

**Comment by panamafrancis** [comment]
so one could make the following calls

GET /resource/id/[1,2,3]
&
GET /resource/id/1

**Comment by smd686s** [comment]
Shouldn't you handle that type of request in a query string on the index (RESTful) route?  Like this:

GET /resource?ids[]=1&ids[]=2&ids[]=3
&
GET /resource/1

**Comment by julienschmidt** [comment]
There is no such thing in the HTTP spec. Neither 1.1 nor 1.0 or 2.0.
What you meant is probably the query, like smd686s described.

If you have a route `/resource/:ids`, `/resource/id/[1,2,3]` would match this route and you could manually parse the IDs.
