### ISSUE TITLE
Native OPTIONS support

### ISSUE THREAD

**Issue by rogpeppe** [julienschmidt/httprouter#98]
In order to implement the HTTP OPTIONS request correctly,
it is necessary to install the options handler on every possible
path in the router. But if this is done, then the NotFound handler
will never be invoked; instead the MethodNotAllowed handler
will be called, which isn't very useful.

I think this could do with a special case - the HandleMethodNotAllowed
should ignore the OPTIONS tree when checking to see if there
is an alternative method defined.

**Comment by julienschmidt** [comment]
Or HttpRouter could get native support. A proper MethodNotAllowed implementation also requires the same `Allow: X,Y,Z` header.

**Comment by jgoerz** [comment]
+1 for native support for MethodNotAllowed.  The same issue exists for NotFound except I don't see a workaround.  This is a problem when you have middleware wrapping the handler functions for logging.  Maybe not an issue for human browsers, but not seeing these "errors" in the log when developing or updating APIs is a bummer.

But this is a small thing.  This software is fantastic.  Thank you for sharing it with us.

**Comment by julienschmidt** [comment]
MethodNotAllowed now ignores `OPTIONS` handlers.
Native support for `OPTIONS` will follow soon™.

**Comment by julienschmidt** [comment]
Very soon™ :wink:
